# Generated by Django 4.0 on 2021-12-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Categoria')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo del Post')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('imagen', models.ImageField(upload_to='post', verbose_name='Imagenes')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': ('Post',),
                'verbose_name_plural': ('Posts',),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('asunto', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': ('Comentario',),
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
