# Generated by Django 4.0 on 2021-12-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_alta',
        ),
    ]
