# Generated by Django 4.0 on 2021-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='categorias/', verbose_name='Imagenes'),
        ),
    ]
